export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const USER_EDIT_FAILURE = 'USER_EDIT_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_ONE_USER_SUCCESS = 'FETCH_ONE_USER_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const START_REQUEST = 'START_REQUEST';
export const TOGGLE_MODAL_LOGIN = 'TOGGLE_MODAL_LOGIN';

export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_DIAGRAM_SUCCESS = 'FETCH_TASKS_DIAGRAM_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_BY_ID_SUCCESS = 'FETCH_CATEGORIES_BY_ID_SUCCESS';
export const FETCH_CATEGORIES_BY_ID_FAILURE = 'FETCH_CATEGORIES_BY_ID_FAILURE';


export const FETCH_TASK_INFO_SUCCESS = 'FETCH_TASK_INFO_SUCCESS';
export const FETCH_TASK_INFO_FAILURE = 'FETCH_TASK_INFO_FAILURE';